CAUGHT Exception from If
CAUGHT Exception from For
